### ISSUE TITLE
basic-ts broken on @playwright/test 0.9.6

### ISSUE THREAD

**Issue by bootstraponline** [microsoft/playwright-test#137]
I updated the`@playwright/test` dev dependency to the latest version `0.9.6` and `npx test-runner --browser-name=chromium` errors with `npm ERR! cb.apply is not a function`

https://github.com/microsoft/playwright-test/blob/master/examples/basic-ts/package.json

```json
 "devDependencies": {
    "@playwright/test": "0.9.1"
  },
```

```
 npx test-runner --browser-name=chromium
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-09-27T19_49_06_428Z-debug.log
Install for [ 'test-runner@latest' ] failed with code 1
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.12.0/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'test-runner@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/mac/.npm/_npx/15808',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.12.0
4 verbose npm-session e3e77b219de67868
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/test-runner 171ms (from cache)
8 silly pacote tag manifest for test-runner@latest fetched in 214ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /usr/local/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:178:5)
10 verbose cwd /Users/mac/code/playwright/basic-ts
11 verbose Darwin 19.6.0
12 verbose argv "/usr/local/Cellar/node/14.12.0/bin/node" "/usr/local/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "test-runner@latest" "--global" "--prefix" "/Users/mac/.npm/_npx/15808" "--loglevel" "error" "--json"
13 verbose node v14.12.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]

```

The error starts in version `"@playwright/test": "0.9.4"`. I can update to `0.9.3` without an error.

**Comment by bootstraponline** [comment]
It looks like playwright is getting confused by `https://github.com/75lb/test-runner.git` as returned by `https://registry.npmjs.org/test-runner`?

**Comment by mxschmitt** [comment]
Could track the change down to the following commit: https://github.com/microsoft/playwright-test/commit/bf80a84b376b2d59ab06d19bbaa76c4c2822867c

@pavelfeldman not sure if it was intended. From my point of view it should be a dependency (because of developer experience).

**Comment by arjunattam** [comment]
This is fixed.
