### ISSUE TITLE
Getting Started in README.md  doesn't work

### ISSUE THREAD

**Issue by YusukeIwaki** [microsoft/playwright-test#188]
I just tried the example in README.md > Getting Started, and an error occured:

```
browserType.launch: No executable path is specified
```

README.md says "**Zero config** cross-browser end-to-end testing", but does some configuration are required at this point?

* macOS BigSur
* Node 14.15.1

## step to reproduce

```
mkdir pl-test/
cd pl-test/
npm init --yes
npm install -D @playwright/test
```

and put a file named 'foo.spec.ts' with the content:

```
import { it, expect } from "@playwright/test";

it("is a basic test with the page", async ({ page }) => {
  await page.goto("https://playwright.dev/");
  const name = await page.innerText(".home-navigation");
  expect(name).toBe("🎭 Playwright");
});
```

and then test it with `npx folio`

## error

```
$ npx folio

Running 3 tests using 3 workers
  1) foo.spec.ts:3:1 › is a basic test with the page ===============================================
     browserName=chromium, headful=false, slowMo=0, video=false, screenshotOnFailure=false

    browserType.launch: No executable path is specified. Pass "executablePath" option directly.
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

     
        at Connection.sendMessageToServer (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/connection.js:69:15)
        at Proxy.<anonymous> (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:54:53)
        at /Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:61:73
        at BrowserType._wrapApiCall (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:80:34)
        at BrowserType.launch (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:52:21)
        at Object.fixtures.browser.init.scope [as fn] (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/@playwright/test/out/index.js:48:39)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:78:52)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)

  2) foo.spec.ts:3:1 › is a basic test with the page ===============================================
     browserName=firefox, headful=false, slowMo=0, video=false, screenshotOnFailure=false

    browserType.launch: No executable path is specified. Pass "executablePath" option directly.
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

     
        at Connection.sendMessageToServer (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/connection.js:69:15)
        at Proxy.<anonymous> (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:54:53)
        at /Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:61:73
        at BrowserType._wrapApiCall (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:80:34)
        at BrowserType.launch (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:52:21)
        at Object.fixtures.browser.init.scope [as fn] (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/@playwright/test/out/index.js:48:39)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:78:52)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)

  3) foo.spec.ts:3:1 › is a basic test with the page ===============================================
     browserName=webkit, headful=false, slowMo=0, video=false, screenshotOnFailure=false

    browserType.launch: No executable path is specified. Pass "executablePath" option directly.
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

     
        at Connection.sendMessageToServer (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/connection.js:69:15)
        at Proxy.<anonymous> (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:54:53)
        at /Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:61:73
        at BrowserType._wrapApiCall (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/channelOwner.js:80:34)
        at BrowserType.launch (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:52:21)
        at Object.fixtures.browser.init.scope [as fn] (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/@playwright/test/out/index.js:48:39)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:78:52)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)
        at Fixture.setup (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:68:25)
        at FixturePool.setupFixtureForRegistration (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/folio/out/fixtures.js:239:9)

  3 failed
    foo.spec.ts:3:1 › is a basic test with the page ================================================
    browserName=chromium, headful=false, slowMo=0, video=false, screenshotOnFailure=false
    foo.spec.ts:3:1 › is a basic test with the page ================================================
    browserName=webkit, headful=false, slowMo=0, video=false, screenshotOnFailure=false
    foo.spec.ts:3:1 › is a basic test with the page ================================================
    browserName=firefox, headful=false, slowMo=0, video=false, screenshotOnFailure=false

```

**Comment by pavelfeldman** [comment]
Is that M1 chip or older Mac with BigSur?

**Comment by YusukeIwaki** [comment]
Chip is Intel. (Macbook 2017)

**Comment by pavelfeldman** [comment]
Then I believe you are using an old version of Playwright. 1.6 should work for you.

**Comment by YusukeIwaki** [comment]
I found that `npm install -D @playwright/test` shows an error.

```
 $ npm install @playwright/test

> playwright@1.6.2 install /Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright
> node install.js

(node:30783) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.1
    at Object.assert (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/install/browserFetcher.js:131:13)
    at Object.downloadBrowserWithProgressBar (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/install/browserFetcher.js:156:17)
    at async validateCache (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/install/installer.js:99:9)
    at async installBrowsersWithProgressBar (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/install/installer.js:56:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pl-test@1.0.0 No description
npm WARN pl-test@1.0.0 No repository field.

+ @playwright/test@0.162.0
added 256 packages from 194 contributors and audited 256 packages in 14.614s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

Sorry, I didn't noticed my macOS is upgraded to macOS 11.1 beta...
The cause is that playwright doesn't support macOS 11.1 at this point.

You can close this issue.

**Comment by YusukeIwaki** [comment]
Playwright 1.7.0 (https://github.com/microsoft/playwright/pull/4724) already solved this issue.
