### ISSUE TITLE
[BUG] folio --help argument tries to read test files in current folder

### ISSUE THREAD

**Issue by jordangarside** [microsoft/playwright-test#200]
```
❯ npx folio --help
npx: installed 234 in 12.63s
Usage:  [options]

Options:
  -V, --version                output the version number
  ...
❯ touch something.test.ts
❯ npx folio --help
npx: installed 234 in 12.723s
Error while reading /Users/jordan.garside/some-folder/something.test.ts:
Cannot find module '@babel/plugin-proposal-class-properties'
Require stack:
```

```
❯ npx folio --version
npx: installed 234 in 9.116s
Version 0.3.16
```

**Comment by yury-s** [comment]
Can reproduce it locally, here is the stack trace:

```sh
$ npx folio --help
npx: installed 234 in 6.392s
Error while reading /home/yurys/sandbox/ttt/something.test.ts:
Cannot find module '@babel/plugin-proposal-class-properties'
Require stack:
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/index.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/index.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/transform.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/runnerSpec.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/runner.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/cli.js
- /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at resolve (internal/modules/cjs/helpers.js:21:19)
    at resolveStandardizedName (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePlugin (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPlugin (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at createDescriptor (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at /home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at cachedFunction (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/gensync/index.js:251:28)
    at sync (/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/gensync/index.js:89:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/config/files/index.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/node_modules/@babel/core/lib/index.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/transform.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/runnerSpec.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/runner.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/out/cli.js',
    '/home/yurys/.npm/_npx/1960849/lib/node_modules/folio/cli.js'
  ]
}
```

**Comment by dgozman** [comment]
See https://github.com/microsoft/folio/issues/110.
