### ISSUE TITLE
Junit.xml Reporter Characters

### ISSUE THREAD

**Issue by BillyBolton** [microsoft/playwright-test#224]
I noticed an issue with the junit reporter character encoding when used with playwright-axe. The issue seems to be exclusive to junit reporter, as opposed to perfect output from the line reporter.

Line Reporter Test Result Output:
..@virtual-machine ~/Desktop/dev/tdd-playwright-example/e2e $ FOLIO_JUNIT_OUTPUT_NAME=test-results/playwright_e2e_junit.xml npx folio --reporter=junit,line --param slowMo=1000 screenshotOnFailure

Running 34 tests using 2 workers
test.spec.ts - Accessibility:  gets and reports a11y for the specific element
┌─────────┬──────────────────┬───────────┬───────────────────────────────────────────────────────────────────┬───────┐
│ (index) │        id        │  impact   │                            description                            │ nodes │
├─────────┼──────────────────┼───────────┼───────────────────────────────────────────────────────────────────┼───────┤
│    0    │ 'document-title' │ 'serious' │ 'Ensures each HTML document contains a non-empty <title> element' │   1   │
│    1    │ 'html-has-lang'  │ 'serious' │        'Ensures every HTML document has a lang attribute'         │   1   │
└─────────┴──────────────────┴───────────┴───────────────────────────────────────────────────────────────────┴───────┘
  1) test/test.spec.ts:166:5 › Accessibility:  gets and reports a11y for the specific element ======

    AssertionError [ERR_ASSERTION]: 2 accessibility violations were detected

        at Object.testResultDependsOnViolations (/home/user/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/utils.js:16:26)
        at /home/user/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/index.js:96:13
        at Generator.next (<anonymous>)
        at fulfilled (/home/user/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/index.js:24:58)

  33 skipped
  1 failed
    test/test.spec.ts:166:5 › Accessibility:  gets and reports a11y for the specific element =======
`

In the xml file though, the encoding is different:
`...
</testcase>
<testcase name="Accessibility:  gets and reports a11y for the specific element" classname="test/test.spec.ts Accessibility: " time="0.611">
<failure message="test.spec.ts:166:5 gets and reports a11y for the specific element" type="FAILURE">
  test/test.spec.ts:166:5 › Accessibility:  gets and reports a11y for the specific element =========

    AssertionError [ERR_ASSERTION]: 2 accessibility violations were detected

        at Object.testResultDependsOnViolations (/home/wbolton/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/utils.js:16:26)
        at /home/wbolton/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/index.js:96:13
        at Generator.next (&lt;anonymous&gt;)
        at fulfilled (/home/wbolton/Desktop/dev/tdd-playwright-example/e2e/node_modules/axe-playwright/dist/index.js:24:58)

</failure>
</testcase>
<system-out>
┌─────────┬──────────────────┬───────────┬───────────────────────────────────────────────────────────────────┬───────┐
│ (index) │        id        │  impact   │                            description                            │ nodes │
├─────────┼──────────────────┼───────────┼───────────────────────────────────────────────────────────────────┼───────┤
│    0    │ [32m'document-title'[39m │ [32m'serious'[39m │ [32m'Ensures each HTML document contains a non-empty &lt;title&gt; element'[39m │   [33m1[39m   │
│    1    │ [32m'html-has-lang'[39m  │ [32m'serious'[39m │        [32m'Ensures every HTML document has a lang attribute'[39m         │   [33m1[39m   │
└─────────┴──────────────────┴───────────┴───────────────────────────────────────────────────────────────────┴───────┘

</system-out>
</testsuite>
</testsuites>`

Is this normal behavior? I've been looking at the modules for far too long. I use CircleCi and there's issues when I store this xml as an artifact.

**Comment by BillyBolton** [comment]
I'm still getting the same issue. Can this be re-opened?
`<testsuites id="" name="" tests="3" failures="3" skipped="0" errors="0" time="20.254">
<testsuite name="tests/foo.spec.ts" timestamp="1618404293678" hostname="" tests="3" failures="3" skipped="0" time="16.142" errors="0">
<testcase name="is a basic test with the page" classname="tests/foo.spec.ts " time="7.535">
<failure message="foo.spec.ts:3:1 is a basic test with the page" type="FAILURE">
  tests/foo.spec.ts:3:1 › [chromium] is a basic test with the page =================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: &amp;quot;2&amp;quot;
    Received: &amp;quot;Playwright&amp;quot;

      4 |     await page.goto(&amp;quot;https://playwright.dev/&amp;quot;);
      5 |     const name = await page.innerText(&amp;quot;.navbar__title&amp;quot;);
    &gt; 6 |     expect(name).toBe(&amp;quot;2&amp;quot;);
        |                  ^
      7 | });

        at Spec.fn (/home/user/Desktop/dev/tdd-playwright-example/e3e/tests/foo.spec.ts:6:18)
        at WorkerRunner._runTestWithBeforeHooks (/home/user/Desktop/dev/tdd-playwright-example/e3e/node_modules/folio/out/workerRunner.js:299:13)`

**Comment by BillyBolton** [comment]
Here is my config file based on the new documentation:
```// config.ts
import { ChromiumEnv, FirefoxEnv, WebKitEnv, test, setConfig } from "@playwright/test";
import { reporters, setReporters } from "@playwright/test";

setConfig({
    testDir: __dirname,  // Search for tests in this directory.
    timeout: 30000,  // Each test is given 30 seconds.
    // timeout: 90000,  // Each test is given 90 seconds.
    retries: 0,  // Failing tests will be retried at most two times.
});

setReporters([
    // Report to the terminal with "line" reporter.
    new reporters.line(),
    // Additionally, output a JUnit XML file.
    new reporters.junit({ outputFile: 'junit.xml', stripANSIControlSequences: true }),
]);

const options = {
    // Launch options:
    headless: true,
    slowMo: 50,
    // Context options:
    viewport: { width: 800, height: 600 },
    ignoreHTTPSErrors: true,
    // Testing options:
    // video: 'retain-on-failure',
    screenshot: 'only-on-failure'
};

// Run tests in three browsers.
test.runWith(new ChromiumEnv(options), { tag: 'chromium' });
test.runWith(new FirefoxEnv(options), { tag: 'firefox' });
test.runWith(new WebKitEnv(options), { tag: 'webkit' });```

**Comment by dgozman** [comment]
@BillyBolton What is the problem in the example you pasted? You don't like `&amp;` escapes? Unfortunately, we'll have to escape at least some characters, e.g. `<`, otherwise it won't be a valid xml file.

**Comment by BillyBolton** [comment]
@dgozman Thanks for getting back to me. Yea the &amp, &quote, &gt aren't playing well. Comparing the line and junit reporters seem to conclude that it's related to ANSI formatting. I try using the new config option,  stripANSIControlSequences: true, but it doesn't seem to make a difference.
