### ISSUE TITLE
globalSetup doesn't run before all tests

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/playwright-test#240]
## Description

`globalSetup` should run before any tests run. However, it seems like `@playwright/test` is running the test (or checking the code) before running the test. This means that even though I define `globalSetup` in my `config.ts` file then set `process.env.STORAGE` and try to use it in a test, playwright thinks it's undefined and exits the runner. 

## Reproduction 

Here is the [repo](https://github.com/jsjoeio/playwright-test-repro). 

1. `git clone https://github.com/jsjoeio/playwright-test-repro.git`
2. `yarn`
3. `yarn test`

### Expected

Global setup should run _then_ tests should run 

### Actual

`@playwright/test` runs tests first:
```js
Error while reading /Users/jp/Dev/playwright-test-repro/hello.test.ts:
Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/jp/Dev/playwright-test-repro/hello.test.ts:8:29
    at describe (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/spec.js:127:9)
    at Object.<anonymous> (/Users/jp/Dev/playwright-test-repro/hello.test.ts:3:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/Users/jp/Dev/playwright-test-repro/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .ts] (/Users/jp/Dev/playwright-test-repro/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Loader.loadTestFile (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/loader.js:60:13)
    at runTests (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/cli.js:130:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Comment by dgozman** [comment]
Interesting... We are reading (require) all tests before running globalSetup and anything else, and this example uses `process.env.STORAGE` at require time.

**Comment by jsjoeio** [comment]
I know that when we were using `jest-playwright`, I had the exact same setup and didn't run into this issue.

I thought I heard somewhere that Jest overwrites `require` which could potentially prevent this error from happening with their test runner. Though I can't find any docs/evidence to support that claim.

In theory though, from a user perspective, this _should_ work, right? Like you want this to work for developers I assume?

**Comment by dgozman** [comment]
Yep, I don't see any major issues with supporting this. Here is PR under review: https://github.com/microsoft/folio/pull/222.

**Comment by jsjoeio** [comment]
Hooray! That's fantastic to hear. Thanks for being so open to feedback!

FWIW, my coworker helped find the Jest overwrite of require: https://github.com/facebook/jest/issues/7722
